language: java
dist: bionic
jdk: openjdk11

services:
  - 'docker'

cache:
  directories:
    - "$HOME/.m2"


install:
  - pwd # just do nothing

script:
  - .travis/build.sh


deploy:
  - provider: script
    script: bash .travis/deploy.sh develop
    on:
      branch: develop
  - provider: script
    script: bash scripts/deploy.sh master
    on:
      tags: true
      branch: master
