language: java

jdk: openjdk11

services:
  - 'docker'

cache:
  directories:
    - "$HOME/.m2"


install:
  - echo "$(pwd)" # just do nothing

before_script:
  - .travis/setup.sh
  - source .travis/maven-informations.sh

script:
  - .travis/build.sh


deploy:
  - provider: script
    script: bash .travis/deploy.sh develop
    on:
      branch: develop
  - provider: script
    script: bash scripts/deploy.sh master
    on:
      tags: true
      branch: master