spring:
  cloud:
    consul:
      discovery:
        healthCheckPath: /management/health
        instanceId: gateway:${spring.application.instance-id:${random.value}}
        service-name: gateway

  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://keycloak:9080/auth/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app

management:
  endpoints:
    web:
      exposure:
        include: ['info', 'health', 'routes']
      base-path: '/management'


zuul: # those values must be configured depending on the application specific needs
  sensitive-headers: Cookie,Set-Cookie #see https://github.com/spring-cloud/spring-cloud-netflix/issues/3126
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
  prefix: /services
  semaphore:
    max-semaphores: 500
  ignoredServices: 'consul,gateway,mongo,keycloak,mariadb' # Prevent Consul and the "gateway" app itself from having a Zuul route automatically created for them
